name: Docker test build

on:
  push:
    branches: master
    tags-ignore:
      - 'v.*'

env:
  DOCKER_IMAGE_REPO: platformengineering
  DOCKER_IMAGE_NAME: snpaas-tools
  DOCKER_BUILD_DIR: docker/snpaas-tools
  VERSION: 3.${{ github.run_number }}.0
  TAG: platformengineering/snpaas-tools

jobs:
  docker-build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the latest Docker image
        run: |
            docker build --file $DOCKER_BUILD_DIR/Dockerfile --tag $TAG $DOCKER_BUILD_DIR
            docker tag $DOCKER_IMAGE_NAME $TAG:$VERSION

      - name: Output
        run: |
            DOCKER_IMAGE=$DOCKER_IMAGE_NAME TTY= ./snpaas

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: springernature/ee-snpaas-cli/${{steps.docker.outputs.name}}
          path: ${{steps.docker.outputs.builddir}}
          dockerfile: ${{steps.docker.outputs.builddir}}/Dockerfile
          add_git_labels: true
          tag_with_ref: true


