name: Docker test build

on:
  push:
    branches: master
    tags-ignore:
      - 'v.*'

env:
  DOCKER_IMAGE_REPO: platformengineering
  DOCKER_IMAGE_NAME: snpaas-tools
  DOCKER_BUILD_DIR: docker/snpaas-tools
  VERSION: 3.${{ github.run_number }}.0
  REGISTRY: ghcr.io
  TAG: platformengineering/snpaas-tools

jobs:
  docker-build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: docker/snpaas-tools
          pull: true
          push: true
          cache-from: type=registry,ref=platformengineering/snpaas-tools:latest
          cache-to: type=inline
          tags: platformengineering/snpaas-tools:latest


