name: Build docker and publish to DockerHub if released

on:
  release:
    types: 
      - published

env:
  RELEASE: snpaas-cli
  TITLE: "SNPaaS client"
  DOCKER_IMAGE_REPO: platformengineering
  DOCKER_IMAGE_NAME: snpaas-tools
  DOCKER_BUILD_DIR: docker/snpaas-tools

jobs:
  push_to_registry:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the git repository
        uses: actions/checkout@v2

      - name: Get metadata for Docker image
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.DOCKER_IMAGE_REPO }}/${{ env.DOCKER_IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push the image if it is a release
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name == 'release' }}
          context: ${{ env.DOCKER_BUILD_DIR }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }
          build-args: |
            VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}

