# When a commit is pushed with text matching v*, i.e. v1.0, v20.15.10, creates a new release
name: Docker build, release and push to DockerHub

on:
  push:
    tags:
    - '*'
    paths:
    - 'docker/**'

env:
  RELEASE: snpaas-cli
  TITLE: "SNPaaS client"
  DOCKER_IMAGE_REPO: platformengineering
  DOCKER_IMAGE_NAME: snpaas-tools
  DOCKER_BUILD_DIR: docker/snpaas-tools
  VERSION: 3.${{ github.run_number }}.0

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.docker.outputs.version }}
      name: ${{ steps.docker.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          echo ${{ secrets.DOCKER_USERNAME }}
          echo ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_IMAGE=${{ env.DOCKER_IMAGE_REPO }}/${{ env.DOCKER_IMAGE_NAME }}
          VERSION=${{ env.VERSION }}
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            VERSION=pr-${{ github.event.number }}
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          if [ "${{ github.event_name }}" = "push" ]; then
            TAGS="$TAGS,${DOCKER_IMAGE}:sha-${GITHUB_SHA::8}"
          fi
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.DOCKER_BUILD_DIR }}
          pull: true
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE_REPO }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          cache-to: type=inline
          push: ${{ github.event_name != 'pull_request' }}
          tags: latest,${{ steps.prep.outputs.tags }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set release variables
        id: release
        run: |
            tag=$(git describe --abbrev=0 --tags)
            prevtag=$(git describe --abbrev=0 --tags "${tag}^")
            changes=$(git log --pretty="%h %aI %s (%an)" "${prevtag}..${tag}" | sed 's/^/- /')
            cat <<EOF > description.md
            # $RELEASE version ${{needs.build.outputs.version}} (build tag: ${tag})
            
            $TITLE
            
            ## Changes since last version
            
            $changes
            
            EOF
            echo ::set-output name=description::$(cat description.md)
            echo ::set-output name=release::$(echo ${RELEASE})
            echo ::set-output name=name::$(echo ${TITLE} version ${{needs.build.outputs.version}})
            echo ::set-output name=tag::$(echo ${tag})
 
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{steps.release.outputs.tag}}
          release_name: ${{steps.release.outputs.name}}
          body_path: description.md
          draft: false
          prerelease: false

