# This is a basic workflow to help you get started with Actions
name: docker-build-commit

on:
  push:
    branches: master
    tags:

jobs:
  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      # Get the repositery's code
      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: Sets docker build variables
        id: vars
        env:
          DOCKER_IMAGE_REPO: platformengineering
          DOCKER_IMAGE_NAME: snpaas-tools 
        run: |
            cd docker/${DOCKER_IMAGE_NAME}
            echo ::set-output name=pwd::$(pwd)
            echo ::set-env name=IMAGE_NAME::$(echo ${DOCKER_IMAGE_NAME})
            echo ::set-env name=IMAGE_REPO::$(echo ${DOCKER_IMAGE_REPO})
            echo ::set-env name=IMAGE_TAG::$(echo ${DOCKER_IMAGE_REPO}/${DOCKER_IMAGE_NAME})
            echo ::set-env name=IMAGE_VERSION::$(sed -ne 's/^ARG.* VERSION=\(.*\)/\1/p' Dockerfile)

      - name: Build the tagged Docker image
        run: |
            cd ${{ steps.vars.outputs.pwd }}
            echo "Building Docker image with tag $IMAGE_TAG:$IMAGE_VERSION ..."
            docker build . --file Dockerfile -t $IMAGE_NAME
            docker tag $IMAGE_NAME $IMAGE_TAG:$IMAGE_VERSION

      - name: Build the latest Docker image
        run: |
            cd ${{ steps.vars.outputs.pwd }}
            docker build . --file Dockerfile --tag $IMAGE_TAG

      - name: Run help
        run: |
            DOCKER_IMAGE=$IMAGE_NAME ./snpaas

