name: Docker test build

on:
  push:
    branches: master
    tags-ignore:
      - 'v.*'

env:
  DOCKER_IMAGE_REPO: platformengineering
  DOCKER_IMAGE_NAME: snpaas-tools
  DOCKER_BUILD_DIR: docker/snpaas-tools

jobs:
  docker-build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set docker build variables
        id: docker
        run: |
            echo ${DOCKER_BUILD_DIR}
            echo 'NAME'=${DOCKER_IMAGE_NAME}) >> $GITHUB_ENV
            echo 'REPO'=${DOCKER_IMAGE_REPO} >> $GITHUB_ENV
            echo 'TAG'=${DOCKER_IMAGE_REPO}/${DOCKER_IMAGE_NAME} >> $GITHUB_ENV
            echo 'BUILDDIR'=${DOCKER_BUILD_DIR} >> $GITHUB_ENV
            echo 'VERSION'=$(sed -ne 's/^ARG.* VERSION=\(.*\)/\1/p' ${DOCKER_BUILD_DIR}/Dockerfile) >> $GITHUB_ENV
            echo ::set-output name=name::$(echo ${DOCKER_IMAGE_NAME} >> $GITHUB_ENV
            echo ::set-output name=builddir::$(echo ${DOCKER_BUILD_DIR})
            echo ::set-output name=version::$(echo ${VERSION})
            echo ::set-output name=tag::$(echo ${DOCKER_IMAGE_REPO}/${DOCKER_IMAGE_NAME})


      - name: Build the latest Docker image
        run: |
            docker build --file $BUILDDIR/Dockerfile --tag $NAME $BUILDDIR
            docker tag $NAME $TAG:$VERSION

      - name: Output
        run: |
            DOCKER_IMAGE=$NAME TTY= ./snpaas

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: springernature/ee-snpaas-cli/${{steps.docker.outputs.name}}
          path: ${{steps.docker.outputs.builddir}}
          dockerfile: ${{steps.docker.outputs.builddir}}/Dockerfile
          add_git_labels: true
          tag_with_ref: true


