name: Docker Build

on:
  push:
    branches: master
    tags:

jobs:
  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set docker build variables
        id: docker
        env:
          DOCKER_IMAGE_REPO: platformengineering
          DOCKER_IMAGE_NAME: snpaas-tools
          DOCKER_BUILD_DIR: docker/snpaas-tools
        run: |
            VERSION=$(sed -ne 's/^ARG.* VERSION=\(.*\)/\1/p' ${DOCKER_BUILD_DIR}/Dockerfile)
            echo ::set-env name=NAME::$(echo ${DOCKER_IMAGE_NAME})
            echo ::set-env name=REPO::$(echo ${DOCKER_IMAGE_REPO})
            echo ::set-env name=TAG::$(echo ${DOCKER_IMAGE_REPO}/${DOCKER_IMAGE_NAME})
            echo ::set-env name=BUILDDIR::$(echo ${DOCKER_BUILD_DIR})
            echo ::set-env name=VERSION::$(echo ${VERSION})
            echo ::set-output name=version::$(echo ${VERSION})
            echo ::set-output name=tag::$(echo ${DOCKER_IMAGE_REPO}/${DOCKER_IMAGE_NAME})

      - name: Build the tagged Docker image
        run: |
            echo "Building Docker image with tag $TAG:$VERSION ..."
            docker build --file $BUILDDIR/Dockerfile --tag $NAME $BUILDDIR
            docker tag $NAME $TAG:$VERSION

      - name: Build the latest Docker image
        run: |
            cd $BUILD
            docker build --file $BUILDDIR/Dockerfile --tag $TAG $BUILDDIR

      - name: Output
        run: |
            DOCKER_IMAGE=$NAME TTY= ./snpaas


